apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nestjs
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      containers:
      - name: nestjs
        image: nestjsmysqlaksdevacr.azurecr.io/nestjs-app:latest #nestjs.azurecr.io/nestjs-app:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 64Mi
            cpu: 128m
        ports:
        - containerPort: 3000
          name: http
        env:
          - name: RESPONSE
            value: "Hello from AKS"