apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nestjs-app
  template:
    metadata:
      labels:
        app: nestjs-app
    spec:
      containers:
      - name: nestjs
        image: nestjs-app.azurecr.io/nestjs-app:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 64Mi
            cpu: 128m
        ports:
        - containerPort: 3000
          name: http
        env:
          - name: RESPONSE
            value: "Hello from AKS"