apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Generate a ConfigMap based on the environment variables in the file `.env`.
configMapGenerator:
  - name: my-config-map
    envs:
      - .env

replacements:
  - source:
      # Replace any matches by the value of environment variable `ACR_NAME`.
      kind: ConfigMap
      name: my-config-map
      fieldPath: data.ACR_NAME
    targets:
      - select:
          # In each Deployment resource …
          kind: Deployment
        fieldPaths:
          # … match the image of container `nginx` …
          - spec.template.spec.containers.[name=nestjs].image
        options:
          # … but replace only the fist part when split by "/".
          delimiter: "/"
          index: 0
  - source:
      # Replace any matches by the value of environment variable `IMAGE_NAME`.
      kind: ConfigMap
      name: my-config-map
      fieldPath: data.IMAGE_NAME
    targets:
      - select:
          # In each Deployment resource …
          kind: Deployment
        fieldPaths:
          # … match the image of container `nginx` …
          - spec.template.spec.containers.[name=nestjs].image
        options:
          # … but replace only the second part when split by "/".
          delimiter: "/"
          index: 1

resources:
  - ../../bases/app/deployment.yaml