name: 'Terraform Deploy'
on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'terraform-live/**'
  #     - 'terraform-modules/**'
  #     - '.github/workflows/**'
  workflow_dispatch:
  #pull_request:

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  GIT_REPOSITORY: https://github.com/leomozzer/nestjs-mysql-aks
  PROJECT_NAME: nestjs-mysql-aks
  TERRAFORM_WORKING_DIR: "terraform-live"
  TERRAFORM_MODULES_DIR: "terraform-modules"
  STORAGE_ACCOUNT_NAME: "nestsjaksstac"

jobs:
  plan:
    name: "Terraform"
    strategy:
      matrix:
        stage: [dev]
    concurrency: ${{ matrix.stage }}
    uses: leomozzer/terraform-template/.github/workflows/terraform-plan.yml@main
    with:
      TERRAFORM_WORKING_DIR: ${{ env.TERRAFORM_WORKING_DIR }}
      TERRAFORM_MODULES_DIR: ${{ env.TERRAFORM_MODULES_DIR }}
      WORKING_DIR: "./"
      RESOURCE_GROUP_NAME: "${{ env.PROJECT_NAME }}-tfstate-${{ matrix.stage }}-rg"
      RESOURCE_GROUP_LOCATION: "eastus"
      STORAGE_ACCOUNT_NAME: "${{ env.STORAGE_ACCOUNT_NAME }}${{ matrix.stage }}"
      CONTAINER_NAME: "states"
      STATE_FILE: "${{ env.PROJECT_NAME }}.tfstate"
      STAGE: ${{ matrix.stage }}
      TAGS: '"UseCase=Terraform" "Environment=${{ matrix.stage }}" "Deployed=GitHub Actions" "Repository=${{ env.GIT_REPOSITORY }}" "RunNumber=${{ github.run_number }}"'
    secrets:
      AZURE_SP: ${{ secrets.AZURE_SP }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

  apply:
    name: "Terraform"
    needs: plan
    strategy:
      matrix:
        stage: [dev]
    concurrency: ${{ matrix.stage }}
    uses: leomozzer/terraform-template/.github/workflows/terraform-apply.yml@main
    with:
      WORKING_DIR: "./"
      STORAGE_ACCOUNT_NAME: "${{ env.STORAGE_ACCOUNT_NAME }}${{ matrix.stage }}"
      CONTAINER_NAME: "plans"
      STAGE: ${{ matrix.stage }}
    secrets:
      AZURE_SP: ${{ secrets.AZURE_SP }}